[global]
repo1-path=/var/lib/pgbackrest
log-level-console=info
log-level-file=debug

[demo]
pg1-host=pg-primary-replic
pg1-host-user=postgres
pg1-path=/var/lib/postgresql/16/main

pg2-host=pg-standby-replic
pg2-host-user=postgres
pg2-path=/var/lib/postgresql/16/main

backup-standby=y
